package com.insurance.policy.presentation.rest;

import com.insurance.policy.application.dto.CreatePolicyInput;
import com.insurance.policy.application.dto.CreatePolicyOutput;
import com.insurance.policy.application.usecase.CreatePolicyUseCase;
import com.insurance.policy.presentation.rest.model.CreatePolicyRequest;
import com.insurance.policy.presentation.rest.model.PolicyResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
 * REST Controller for Policy operations.
 *
 * Handles HTTP requests and delegates to use cases.
 * Part of the presentation layer in Clean Architecture.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 */
@RestController
@RequestMapping("/api/v1/policies")
@Tag(name = "Policy Management", description = "APIs for managing insurance policies")
public class PolicyController {

    private static final Logger log = LoggerFactory.getLogger(PolicyController.class);

    private final CreatePolicyUseCase createPolicyUseCase;

    public PolicyController(CreatePolicyUseCase createPolicyUseCase) {
        this.createPolicyUseCase = createPolicyUseCase;
    }

    @PostMapping
    @Operation(summary = "Create a new insurance policy", description = "Creates a new policy with coverages")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "201", description = "Policy created successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid request data"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public ResponseEntity<PolicyResponse> createPolicy(@Valid @RequestBody CreatePolicyRequest request) {
        log.info("Received request to create policy for customer: {}", request.customerId());

        // Convert REST request to use case input
        CreatePolicyInput input = new CreatePolicyInput(
                request.customerId(),
                request.effectiveDate(),
                request.coverages()
        );

        // Execute use case
        CreatePolicyOutput output = createPolicyUseCase.execute(input);

        // Convert use case output to REST response
        PolicyResponse response = PolicyResponse.from(output);

        log.info("Policy created successfully: {}", response.policyNumber());

        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    @GetMapping("/health")
    @Operation(summary = "Health check", description = "Simple health check endpoint")
    public ResponseEntity<String> health() {
        return ResponseEntity.ok("Policy Service is running");
    }
}
