package com.insurance.policy.infrastructure.adapter.persistence;

import com.insurance.policy.domain.entity.Claim;
import com.insurance.policy.domain.port.ClaimRepository;
import com.insurance.policy.domain.valueobject.ClaimNumber;
import com.insurance.policy.domain.valueobject.ClaimStatus;
import com.insurance.policy.infrastructure.adapter.persistence.entity.ClaimJpaEntity;
import com.insurance.policy.infrastructure.adapter.persistence.mapper.ClaimMapper;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * JPA implementation of ClaimRepository.
 *
 * This adapter implements the domain repository interface using Spring Data JPA.
 * It resides in the infrastructure layer and handles persistence details.
 * Maps between domain entities and JPA entities to maintain Clean Architecture.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 * @version 1.0
 */
@Repository
public class ClaimRepositoryAdapter implements ClaimRepository {

    private final ClaimSpringDataRepository springDataRepository;

    public ClaimRepositoryAdapter(ClaimSpringDataRepository springDataRepository) {
        this.springDataRepository = springDataRepository;
    }

    @Override
    public Claim save(Claim claim) {
        ClaimJpaEntity jpaEntity = ClaimMapper.toJpa(claim);
        ClaimJpaEntity saved = springDataRepository.save(jpaEntity);
        return ClaimMapper.toDomain(saved);
    }

    @Override
    public Optional<Claim> findById(Long id) {
        return springDataRepository.findById(id)
                .map(ClaimMapper::toDomain);
    }

    @Override
    public List<Claim> findAll() {
        return springDataRepository.findAll().stream()
                .map(ClaimMapper::toDomain)
                .collect(Collectors.toList());
    }

    @Override
    public void deleteById(Long id) {
        springDataRepository.deleteById(id);
    }

    @Override
    public boolean existsById(Long id) {
        return springDataRepository.existsById(id);
    }

    @Override
    public Optional<Claim> findByClaimNumber(ClaimNumber claimNumber) {
        return springDataRepository.findByClaimNumber(claimNumber.value())
                .map(ClaimMapper::toDomain);
    }

    @Override
    public List<Claim> findByStatus(ClaimStatus status) {
        return springDataRepository.findByStatus(status).stream()
                .map(ClaimMapper::toDomain)
                .collect(Collectors.toList());
    }

    @Override
    public List<Claim> findByPolicyId(String policyId) {
        return springDataRepository.findByPolicyId(policyId).stream()
                .map(ClaimMapper::toDomain)
                .collect(Collectors.toList());
    }
}
