package com.insurance.policy.infrastructure.adapter.persistence;

import com.insurance.policy.domain.valueobject.ClaimStatus;
import com.insurance.policy.infrastructure.adapter.persistence.entity.ClaimJpaEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;
import java.util.Optional;

/**
 * Spring Data JPA repository for ClaimJpaEntity.
 *
 * Provides CRUD operations and custom queries for database access.
 * Used internally by ClaimRepositoryAdapter.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 * @version 1.0
 */
public interface ClaimSpringDataRepository extends JpaRepository<ClaimJpaEntity, Long> {

    /**
     * Find claim by claim number.
     *
     * @param claimNumber the claim number
     * @return Optional containing the claim if found
     */
    Optional<ClaimJpaEntity> findByClaimNumber(String claimNumber);

    /**
     * Find all claims with a specific status.
     *
     * @param status the claim status
     * @return list of claims with the status
     */
    List<ClaimJpaEntity> findByStatus(ClaimStatus status);

    /**
     * Find all claims for a specific policy.
     *
     * @param policyId the policy ID
     * @return list of claims for the policy
     */
    List<ClaimJpaEntity> findByPolicyId(String policyId);
}
