package com.insurance.policy.infrastructure.adapter.persistence;

import com.insurance.policy.infrastructure.adapter.persistence.entity.PolicyJpaEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

/**
 * Spring Data JPA Repository for Policy persistence.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 */
@Repository
public interface PolicyJpaRepository extends JpaRepository<PolicyJpaEntity, Long> {

    Optional<PolicyJpaEntity> findByPolicyNumber(String policyNumber);

    List<PolicyJpaEntity> findByCustomerId(String customerId);
}
