package com.insurance.policy.infrastructure.adapter.persistence;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.insurance.policy.domain.entity.Policy;
import com.insurance.policy.domain.port.PolicyRepository;
import com.insurance.policy.domain.valueobject.*;
import com.insurance.policy.infrastructure.adapter.persistence.entity.PolicyJpaEntity;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * Adapter implementing PolicyRepository using Spring Data JPA.
 *
 * Translates between domain entities and JPA entities (Hexagonal Architecture).
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 */
@Component
public class PolicyRepositoryAdapter implements PolicyRepository {

    private final PolicySpringDataRepository jpaRepository;
    private final ObjectMapper objectMapper;

    public PolicyRepositoryAdapter(PolicySpringDataRepository jpaRepository, ObjectMapper objectMapper) {
        this.jpaRepository = jpaRepository;
        this.objectMapper = objectMapper;
    }

    @Override
    public Policy save(Policy policy) {
        PolicyJpaEntity jpaEntity = toJpaEntity(policy);
        PolicyJpaEntity saved = jpaRepository.save(jpaEntity);
        return toDomainEntity(saved);
    }

    @Override
    public Optional<Policy> findById(Long id) {
        return jpaRepository.findById(id)
                .map(this::toDomainEntity);
    }

    @Override
    public Optional<Policy> findByPolicyNumber(PolicyNumber policyNumber) {
        return jpaRepository.findByPolicyNumber(policyNumber.value())
                .map(this::toDomainEntity);
    }

    @Override
    public List<Policy> findByCustomerId(String customerId) {
        return jpaRepository.findByCustomerId(customerId).stream()
                .map(this::toDomainEntity)
                .collect(Collectors.toList());
    }

    @Override
    public List<Policy> findAll() {
        return jpaRepository.findAll().stream()
                .map(this::toDomainEntity)
                .collect(Collectors.toList());
    }

    @Override
    public void deleteById(Long id) {
        jpaRepository.deleteById(id);
    }

    @Override
    public boolean existsById(Long id) {
        return jpaRepository.existsById(id);
    }

    // Mapping methods

    private PolicyJpaEntity toJpaEntity(Policy policy) {
        PolicyJpaEntity jpaEntity = new PolicyJpaEntity();
        jpaEntity.setId(policy.getId());
        jpaEntity.setPolicyNumber(policy.getPolicyNumber().value());
        jpaEntity.setCustomerId(policy.getCustomerId());
        jpaEntity.setEffectiveDate(policy.getEffectiveDate());
        jpaEntity.setExpirationDate(policy.getExpirationDate());
        jpaEntity.setTotalPremiumAmount(policy.getTotalPremium().amount());
        jpaEntity.setTotalPremiumCurrency(policy.getTotalPremium().currency());
        jpaEntity.setStatus(policy.getStatus());

        // Serialize coverages to JSON
        try {
            String coveragesJson = objectMapper.writeValueAsString(
                    policy.getCoverages().stream()
                            .map(c -> new CoverageDto(c.coverageType(),
                                    c.premiumAmount().amount().doubleValue(),
                                    c.premiumAmount().currency()))
                            .collect(Collectors.toList())
            );
            jpaEntity.setCoveragesJson(coveragesJson);
        } catch (JsonProcessingException e) {
            throw new RuntimeException("Failed to serialize coverages", e);
        }

        return jpaEntity;
    }

    private Policy toDomainEntity(PolicyJpaEntity jpaEntity) {
        // Deserialize coverages from JSON
        List<Coverage> coverages;
        try {
            CoverageDto[] coverageDtos = objectMapper.readValue(
                    jpaEntity.getCoveragesJson(), CoverageDto[].class);
            coverages = new ArrayList<>();
            for (CoverageDto dto : coverageDtos) {
                coverages.add(Coverage.of(dto.coverageType(), dto.premiumAmount(), dto.currency()));
            }
        } catch (JsonProcessingException e) {
            throw new RuntimeException("Failed to deserialize coverages", e);
        }

        // Use reflection to create Policy with ID (for simplicity)
        Policy policy = new Policy(
                jpaEntity.getCustomerId(),
                jpaEntity.getEffectiveDate(),
                coverages
        );

        // Set ID using reflection or a package-private setter
        try {
            var idField = Policy.class.getDeclaredField("id");
            idField.setAccessible(true);
            idField.set(policy, jpaEntity.getId());

            var policyNumberField = Policy.class.getDeclaredField("policyNumber");
            policyNumberField.setAccessible(true);
            policyNumberField.set(policy, PolicyNumber.of(jpaEntity.getPolicyNumber()));

            var statusField = Policy.class.getDeclaredField("status");
            statusField.setAccessible(true);
            statusField.set(policy, jpaEntity.getStatus());
        } catch (Exception e) {
            throw new RuntimeException("Failed to reconstruct domain entity", e);
        }

        return policy;
    }

    // Internal DTO for JSON serialization
    private record CoverageDto(String coverageType, double premiumAmount, String currency) {
    }
}
