package com.insurance.policy.application.service;

import com.insurance.policy.application.dto.CoverageDto;
import com.insurance.policy.application.dto.CreatePolicyInput;
import com.insurance.policy.application.dto.CreatePolicyOutput;
import com.insurance.policy.domain.entity.Policy;
import com.insurance.policy.domain.port.PolicyRepository;
import com.insurance.policy.domain.valueobject.Coverage;
import com.insurance.policy.domain.valueobject.Money;
import com.insurance.policy.domain.valueobject.PolicyNumber;
import com.insurance.policy.domain.valueobject.PolicyStatus;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDate;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

/**
 * Unit tests for CreatePolicyService.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 */
@ExtendWith(MockitoExtension.class)
@DisplayName("Create Policy Service Tests")
class CreatePolicyServiceTest {

    @Mock
    private PolicyRepository policyRepository;

    private CreatePolicyService createPolicyService;

    @BeforeEach
    void setUp() {
        createPolicyService = new CreatePolicyService(policyRepository);
    }

    @Test
    @DisplayName("Should create policy successfully")
    void shouldCreatePolicySuccessfully() {
        // Arrange
        CreatePolicyInput input = new CreatePolicyInput(
                "CUST-001",
                LocalDate.now().plusDays(1),
                List.of(
                        new CoverageDto("Liability", 500.00, "USD"),
                        new CoverageDto("Collision", 300.00, "USD")
                )
        );

        Policy mockSavedPolicy = new Policy(
                input.customerId(),
                input.effectiveDate(),
                List.of(
                        Coverage.of("Liability", 500.00, "USD"),
                        Coverage.of("Collision", 300.00, "USD")
                )
        );

        when(policyRepository.save(any(Policy.class))).thenReturn(mockSavedPolicy);

        // Act
        CreatePolicyOutput output = createPolicyService.execute(input);

        // Assert
        assertNotNull(output);
        assertNotNull(output.policyNumber());
        assertEquals(PolicyStatus.DRAFT, output.status());
        assertEquals(Money.of(800.00, "USD"), output.totalPremium());

        verify(policyRepository, times(1)).save(any(Policy.class));
    }

    @Test
    @DisplayName("Should throw exception when policy repository fails")
    void shouldThrowExceptionWhenRepositoryFails() {
        // Arrange
        CreatePolicyInput input = new CreatePolicyInput(
                "CUST-001",
                LocalDate.now().plusDays(1),
                List.of(new CoverageDto("Liability", 500.00, "USD"))
        );

        when(policyRepository.save(any(Policy.class)))
                .thenThrow(new RuntimeException("Database error"));

        // Act & Assert
        assertThrows(RuntimeException.class, () ->
                createPolicyService.execute(input)
        );

        verify(policyRepository, times(1)).save(any(Policy.class));
    }
}
