package com.insurance.policy.application.dto;

import com.insurance.policy.domain.entity.Policy;
import com.insurance.policy.domain.valueobject.Money;
import com.insurance.policy.domain.valueobject.PolicyNumber;
import com.insurance.policy.domain.valueobject.PolicyStatus;

/**
 * Output DTO for CreatePolicy use case.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 */
public record CreatePolicyOutput(
    PolicyNumber policyNumber,
    Money totalPremium,
    PolicyStatus status
) {
    /**
     * Factory method from domain entity.
     */
    public static CreatePolicyOutput from(Policy policy) {
        return new CreatePolicyOutput(
                policy.getPolicyNumber(),
                policy.getTotalPremium(),
                policy.getStatus()
        );
    }
}
