package com.insurance.policy.application.dto;

import jakarta.validation.constraints.*;
import java.time.LocalDate;
import java.util.List;

/**
 * Input DTO for CreatePolicy use case.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 */
public record CreatePolicyInput(
    @NotBlank(message = "Customer ID is required")
    String customerId,

    @NotNull(message = "Effective date is required")
    @Future(message = "Effective date must be in the future")
    LocalDate effectiveDate,

    @NotEmpty(message = "At least one coverage is required")
    List<CoverageDto> coverages
) {
    public CreatePolicyInput {
        if (effectiveDate != null && effectiveDate.isBefore(LocalDate.now())) {
            throw new IllegalArgumentException("Effective date must be in the future");
        }
    }
}
