package com.insurance.policy.application.dto;

import jakarta.validation.constraints.*;
import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Input DTO for SubmitClaim use case.
 *
 * This Record represents the input data for submitting a new insurance claim.
 * It is immutable and validates itself on construction.
 * Uses Jakarta Bean Validation annotations for declarative validation.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 * @version 1.0
 */
public record SubmitClaimInput(
    @NotNull(message = "Policy ID is required")
    Long policyId,

    @NotNull(message = "Claimed amount is required")
    @DecimalMin(value = "0.01", message = "Claimed amount must be greater than zero")
    BigDecimal claimedAmount,

    @NotNull(message = "Incident date is required")
    @PastOrPresent(message = "Incident date cannot be in the future")
    LocalDate incidentDate,

    @NotBlank(message = "Description is required")
    @Size(min = 10, max = 1000, message = "Description must be between 10 and 1000 characters")
    String description,

    @NotBlank(message = "Currency is required")
    @Size(min = 3, max = 3, message = "Currency must be a 3-letter code (e.g., USD)")
    String currency
) {

    /**
     * Compact constructor with additional validation logic.
     *
     * @throws IllegalArgumentException if business validation fails
     */
    public SubmitClaimInput {
        // Normalize currency to uppercase
        if (currency != null) {
            currency = currency.toUpperCase();
        }

        // Additional business rule: claimed amount cannot exceed a reasonable limit
        if (claimedAmount != null && claimedAmount.compareTo(new BigDecimal("10000000")) > 0) {
            throw new IllegalArgumentException("Claimed amount cannot exceed 10,000,000");
        }
    }
}
