package com.insurance.policy.application.dto;

import com.insurance.policy.domain.entity.Claim;
import com.insurance.policy.domain.valueobject.ClaimStatus;
import java.time.LocalDateTime;

/**
 * Output DTO for SubmitClaim use case.
 *
 * This Record represents the output data returned after successfully submitting a claim.
 * It is immutable and contains only the data needed by the caller.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 * @version 1.0
 */
public record SubmitClaimOutput(
    Long claimId,
    String claimNumber,
    String status,
    LocalDateTime submittedAt
) {

    /**
     * Factory method to create output from domain entity.
     *
     * @param claim the domain entity
     * @return output DTO
     */
    public static SubmitClaimOutput from(Claim claim) {
        return new SubmitClaimOutput(
            claim.getId(),
            claim.getClaimNumber().value(),
            claim.getStatus().name(),
            claim.getSubmittedDate().atStartOfDay()
        );
    }
}
