package com.insurance.policy.domain.entity;

import com.insurance.policy.domain.valueobject.*;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Policy domain entity representing an insurance policy.
 *
 * This is an aggregate root in DDD terms - it controls access to Coverage entities.
 * Contains business logic for policy management and enforces invariants.
 * No framework dependencies - pure domain logic.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 * @version 1.0
 */
public class Policy {

    private Long id;
    private PolicyNumber policyNumber;
    private String customerId;
    private LocalDate effectiveDate;
    private LocalDate expirationDate;
    private List<Coverage> coverages;
    private Money totalPremium;
    private PolicyStatus status;

    /**
     * Constructor for creating a new policy.
     * Enforces invariants: customerId required, effectiveDate in future, at least one coverage.
     *
     * @param customerId the customer ID
     * @param effectiveDate when the policy becomes effective
     * @param coverages list of coverages
     * @throws IllegalArgumentException if validation fails
     */
    public Policy(String customerId, LocalDate effectiveDate, List<Coverage> coverages) {
        validateCustomerId(customerId);
        validateEffectiveDate(effectiveDate);
        validateCoverages(coverages);

        this.customerId = customerId;
        this.effectiveDate = effectiveDate;
        this.expirationDate = effectiveDate.plusYears(1); // Default 1 year
        this.coverages = new ArrayList<>(coverages);
        this.status = PolicyStatus.DRAFT;
        this.totalPremium = calculateTotalPremium();
        this.policyNumber = PolicyNumber.generate(effectiveDate.getYear());
    }

    /**
     * Default constructor for ORM frameworks.
     * Should not be used in business logic.
     */
    protected Policy() {
        this.coverages = new ArrayList<>();
    }

    // Business Methods

    /**
     * Activate the policy.
     * Transitions status from DRAFT to ACTIVE.
     *
     * @throws IllegalStateException if policy is not in DRAFT status
     */
    public void activate() {
        if (status != PolicyStatus.DRAFT) {
            throw new IllegalStateException("Can only activate policies in DRAFT status");
        }
        if (effectiveDate.isAfter(LocalDate.now())) {
            throw new IllegalStateException("Cannot activate policy before effective date");
        }
        this.status = PolicyStatus.ACTIVE;
    }

    /**
     * Cancel the policy.
     * Transitions status to CANCELLED.
     *
     * @throws IllegalStateException if policy is already expired or cancelled
     */
    public void cancel() {
        if (status == PolicyStatus.EXPIRED || status == PolicyStatus.CANCELLED) {
            throw new IllegalStateException("Cannot cancel expired or already cancelled policy");
        }
        this.status = PolicyStatus.CANCELLED;
    }

    /**
     * Add a coverage to the policy.
     * Recalculates total premium.
     *
     * @param coverage the coverage to add
     * @throws IllegalStateException if policy is not in DRAFT status
     */
    public void addCoverage(Coverage coverage) {
        if (status != PolicyStatus.DRAFT) {
            throw new IllegalStateException("Can only add coverages to DRAFT policies");
        }
        if (coverage == null) {
            throw new IllegalArgumentException("Coverage cannot be null");
        }
        this.coverages.add(coverage);
        this.totalPremium = calculateTotalPremium();
    }

    /**
     * Check if the policy is currently active.
     *
     * @return true if active and within effective dates
     */
    public boolean isActive() {
        LocalDate now = LocalDate.now();
        return status == PolicyStatus.ACTIVE &&
                !now.isBefore(effectiveDate) &&
                !now.isAfter(expirationDate);
    }

    // Private helper methods

    private Money calculateTotalPremium() {
        return coverages.stream()
                .map(Coverage::premiumAmount)
                .reduce(Money.ZERO_USD, Money::add);
    }

    private void validateCustomerId(String customerId) {
        if (customerId == null || customerId.trim().isEmpty()) {
            throw new IllegalArgumentException("Customer ID is required");
        }
    }

    private void validateEffectiveDate(LocalDate effectiveDate) {
        if (effectiveDate == null) {
            throw new IllegalArgumentException("Effective date is required");
        }
        if (effectiveDate.isBefore(LocalDate.now())) {
            throw new IllegalArgumentException("Effective date must be in the future");
        }
    }

    private void validateCoverages(List<Coverage> coverages) {
        if (coverages == null || coverages.isEmpty()) {
            throw new IllegalArgumentException("Policy must have at least one coverage");
        }
    }

    // Getters

    public Long getId() {
        return id;
    }

    public PolicyNumber getPolicyNumber() {
        return policyNumber;
    }

    public String getCustomerId() {
        return customerId;
    }

    public LocalDate getEffectiveDate() {
        return effectiveDate;
    }

    public LocalDate getExpirationDate() {
        return expirationDate;
    }

    public List<Coverage> getCoverages() {
        return Collections.unmodifiableList(coverages);
    }

    public Money getTotalPremium() {
        return totalPremium;
    }

    public PolicyStatus getStatus() {
        return status;
    }

    // Package-private setters (for ORM)

    void setId(Long id) {
        this.id = id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Policy policy = (Policy) o;
        return id != null && id.equals(policy.id);
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }

    @Override
    public String toString() {
        return "Policy{" +
                "id=" + id +
                ", policyNumber=" + policyNumber +
                ", customerId='" + customerId + '\'' +
                ", status=" + status +
                ", totalPremium=" + totalPremium +
                '}';
    }
}
