-- Schema for Insurance Policy Service
-- Generated by BMAD Spring Boot Clean Architecture Generator

-- Policies Table
CREATE TABLE IF NOT EXISTS policies (
    id BIGSERIAL PRIMARY KEY,
    policy_number VARCHAR(255) NOT NULL UNIQUE,
    customer_id VARCHAR(255) NOT NULL,
    effective_date DATE NOT NULL,
    expiration_date DATE NOT NULL,
    total_premium_amount NUMERIC(19, 2) NOT NULL,
    total_premium_currency VARCHAR(3) NOT NULL,
    status VARCHAR(20) NOT NULL,
    coverages_json TEXT
);

CREATE INDEX IF NOT EXISTS idx_policies_customer_id ON policies(customer_id);
CREATE INDEX IF NOT EXISTS idx_policies_status ON policies(status);

-- Claims Table
CREATE TABLE IF NOT EXISTS claims (
    id BIGSERIAL PRIMARY KEY,
    claim_number VARCHAR(255) NOT NULL UNIQUE,
    claimed_amount NUMERIC(19, 2) NOT NULL,
    claimed_currency VARCHAR(3) NOT NULL,
    incident_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    submitted_date DATE NOT NULL,
    policy_id VARCHAR(255) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_claims_policy_id ON claims(policy_id);
CREATE INDEX IF NOT EXISTS idx_claims_status ON claims(status);
CREATE INDEX IF NOT EXISTS idx_claims_claim_number ON claims(claim_number);
