package com.insurance.policy;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Insurance Policy Service - Spring Boot Application.
 *
 * Enterprise microservice built with Clean Architecture principles.
 * Manages insurance policies with Domain-Driven Design patterns.
 *
 * Clean Architecture Layers:
 * - Domain: Pure business logic (entities, value objects, repository interfaces)
 * - Application: Use cases and orchestration (services, DTOs)
 * - Infrastructure: Technical implementations (JPA, external APIs, config)
 * - Presentation: REST API controllers and exception handling
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 * @version 1.0
 */
@SpringBootApplication
public class InsurancePolicyApplication {

    public static void main(String[] args) {
        SpringApplication.run(InsurancePolicyApplication.class, args);
    }
}
