package com.insurance.policy.application.usecase;

import com.insurance.policy.application.dto.CreatePolicyInput;
import com.insurance.policy.application.dto.CreatePolicyOutput;

/**
 * Use case for creating a new insurance policy.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 */
public interface CreatePolicyUseCase {

    /**
     * Execute the create policy use case.
     *
     * @param input the policy creation input
     * @return the created policy output
     */
    CreatePolicyOutput execute(CreatePolicyInput input);
}
