package com.insurance.policy.application.usecase;

import com.insurance.policy.application.dto.SubmitClaimInput;
import com.insurance.policy.application.dto.SubmitClaimOutput;

/**
 * Use case interface for submitting a new insurance claim.
 *
 * This interface defines the contract for the use case in the application layer.
 * It follows the Single Responsibility Principle - one use case, one responsibility.
 *
 * Business Rules:
 * - Policy must exist and be active
 * - Claimed amount must be positive
 * - Incident date must be in the past or present
 * - Claim number is auto-generated in format CLM-YYYY-NNNNNN
 * - Initial status is always SUBMITTED
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 * @version 1.0
 */
public interface SubmitClaimUseCase {

    /**
     * Execute the SubmitClaim use case.
     *
     * Submits a new insurance claim for an existing policy.
     * Validates the policy exists and is active, validates the claimed amount,
     * creates a new Claim entity, generates a unique claim number, and persists it.
     *
     * @param input the use case input data containing claim details
     * @return the use case output data with claim ID, number, status, and timestamp
     * @throws PolicyNotFoundException if the referenced policy does not exist
     * @throws IllegalArgumentException if validation fails or policy is not active
     * @throws IllegalStateException if claim submission fails due to business rules
     */
    SubmitClaimOutput execute(SubmitClaimInput input);
}
