package com.insurance.policy.presentation.rest.model;

import com.insurance.policy.application.dto.SubmitClaimOutput;
import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * REST API response model for claim operations.
 *
 * This record represents the HTTP response body returned after successfully
 * submitting a claim. It contains only the information needed by API consumers.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 */
@Schema(description = "Response after successfully submitting a claim")
public record ClaimResponse(

    @Schema(
        description = "Unique identifier of the claim",
        example = "12345"
    )
    Long claimId,

    @Schema(
        description = "Auto-generated claim number in format CLM-YYYY-NNNNNN",
        example = "CLM-2024-000001"
    )
    String claimNumber,

    @Schema(
        description = "Current status of the claim",
        example = "SUBMITTED",
        allowableValues = {"SUBMITTED", "UNDER_REVIEW", "APPROVED", "REJECTED", "PAID"}
    )
    String status,

    @Schema(
        description = "Timestamp when the claim was submitted",
        example = "2024-01-15T10:30:00"
    )
    LocalDateTime submittedAt,

    @Schema(
        description = "Policy ID for which the claim was submitted",
        example = "12345"
    )
    Long policyId,

    @Schema(
        description = "Amount claimed",
        example = "5000.00"
    )
    BigDecimal claimedAmount
) {

    /**
     * Factory method to create a ClaimResponse from use case output.
     *
     * This method converts the application layer DTO to a presentation layer DTO,
     * separating concerns and allowing for API-specific transformations.
     *
     * @param output the use case output DTO
     * @param policyId the policy ID (needed as it's not in output)
     * @param claimedAmount the claimed amount (needed as it's not in output)
     * @return a ClaimResponse ready for HTTP serialization
     */
    public static ClaimResponse from(SubmitClaimOutput output, Long policyId, BigDecimal claimedAmount) {
        return new ClaimResponse(
            output.claimId(),
            output.claimNumber(),
            output.status(),
            output.submittedAt(),
            policyId,
            claimedAmount
        );
    }
}
