package com.insurance.policy.presentation.rest.model;

import com.insurance.policy.application.dto.CoverageDto;
import jakarta.validation.constraints.*;

import java.time.LocalDate;
import java.util.List;

/**
 * REST API request model for creating a policy.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 */
public record CreatePolicyRequest(
    @NotBlank(message = "Customer ID is required")
    String customerId,

    @NotNull(message = "Effective date is required")
    @Future(message = "Effective date must be in the future")
    LocalDate effectiveDate,

    @NotEmpty(message = "At least one coverage is required")
    List<CoverageDto> coverages
) {
}
