package com.insurance.policy.presentation.rest.model;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.*;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * REST API request model for creating a claim.
 *
 * This record represents the HTTP request body for submitting a new insurance claim.
 * It uses Jakarta Bean Validation for automatic validation and OpenAPI annotations
 * for API documentation.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 */
@Schema(description = "Request to submit a new insurance claim")
public record CreateClaimRequest(

    @NotNull(message = "Policy ID is required")
    @Positive(message = "Policy ID must be positive")
    @Schema(
        description = "ID of the policy for which the claim is being submitted",
        example = "12345",
        required = true
    )
    Long policyId,

    @NotNull(message = "Claimed amount is required")
    @DecimalMin(value = "0.01", message = "Claimed amount must be greater than zero")
    @Digits(integer = 10, fraction = 2, message = "Claimed amount must have at most 10 integer digits and 2 decimal places")
    @Schema(
        description = "Amount being claimed in the specified currency",
        example = "5000.00",
        required = true
    )
    BigDecimal claimedAmount,

    @NotNull(message = "Incident date is required")
    @PastOrPresent(message = "Incident date cannot be in the future")
    @Schema(
        description = "Date when the incident occurred",
        example = "2024-01-15",
        required = true
    )
    LocalDate incidentDate,

    @NotBlank(message = "Description is required")
    @Size(min = 10, max = 1000, message = "Description must be between 10 and 1000 characters")
    @Schema(
        description = "Detailed description of the claim and incident",
        example = "Vehicle collision at intersection causing front bumper damage",
        required = true,
        minLength = 10,
        maxLength = 1000
    )
    String description,

    @NotBlank(message = "Currency is required")
    @Pattern(regexp = "^[A-Z]{3}$", message = "Currency must be a valid 3-letter ISO code (e.g., USD, EUR, GBP)")
    @Schema(
        description = "Currency code in ISO 4217 format",
        example = "USD",
        required = true,
        pattern = "^[A-Z]{3}$"
    )
    String currency
) {
}
