package com.insurance.policy.presentation.rest.model;

import com.insurance.policy.application.dto.CreatePolicyOutput;

import java.math.BigDecimal;

/**
 * REST API response model for policy operations.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 */
public record PolicyResponse(
    String policyNumber,
    BigDecimal totalPremiumAmount,
    String totalPremiumCurrency,
    String status
) {
    public static PolicyResponse from(CreatePolicyOutput output) {
        return new PolicyResponse(
                output.policyNumber().value(),
                output.totalPremium().amount(),
                output.totalPremium().currency(),
                output.status().name()
        );
    }
}
