package com.insurance.policy.infrastructure.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import io.swagger.v3.oas.models.servers.Server;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

/**
 * OpenAPI Configuration for Swagger UI Documentation.
 *
 * Accessible at: http://localhost:8080/swagger-ui.html
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 */
@Configuration
public class OpenApiConfig {

    @Bean
    public OpenAPI insurancePolicyOpenAPI() {
        Server devServer = new Server();
        devServer.setUrl("http://localhost:8080");
        devServer.setDescription("Development Server");

        Contact contact = new Contact();
        contact.setEmail("support@insurance.com");
        contact.setName("Insurance Policy Service Team");

        License license = new License()
                .name("MIT License")
                .url("https://choosealicense.com/licenses/mit/");

        Info info = new Info()
                .title("Insurance Policy Service API")
                .version("1.0.0")
                .contact(contact)
                .description("RESTful API for managing insurance policies with Clean Architecture")
                .termsOfService("https://insurance.com/terms")
                .license(license);

        return new OpenAPI()
                .info(info)
                .servers(List.of(devServer));
    }
}
