package com.insurance.policy.infrastructure.adapter.persistence.entity;

import com.insurance.policy.domain.valueobject.ClaimStatus;
import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * JPA Entity for Claim persistence.
 *
 * This is the infrastructure layer representation with JPA annotations.
 * It maps to the database table and handles persistence concerns.
 * Separated from domain entity to maintain Clean Architecture.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 * @version 1.0
 */
@Entity
@Table(name = "claims")
public class ClaimJpaEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "claim_number", unique = true, nullable = false)
    private String claimNumber;

    @Column(name = "claimed_amount", nullable = false, precision = 19, scale = 2)
    private BigDecimal claimedAmount;

    @Column(name = "claimed_currency", nullable = false)
    private String claimedCurrency;

    @Column(name = "incident_date", nullable = false)
    private LocalDate incidentDate;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private ClaimStatus status;

    @Column(name = "submitted_date", nullable = false)
    private LocalDate submittedDate;

    @Column(name = "policy_id", nullable = false)
    private String policyId;

    /**
     * Default constructor for JPA.
     */
    public ClaimJpaEntity() {
    }

    /**
     * Constructor with all fields.
     */
    public ClaimJpaEntity(String claimNumber, BigDecimal claimedAmount, String claimedCurrency,
                          LocalDate incidentDate, ClaimStatus status, LocalDate submittedDate,
                          String policyId) {
        this.claimNumber = claimNumber;
        this.claimedAmount = claimedAmount;
        this.claimedCurrency = claimedCurrency;
        this.incidentDate = incidentDate;
        this.status = status;
        this.submittedDate = submittedDate;
        this.policyId = policyId;
    }

    // Getters and Setters (required by JPA)

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getClaimNumber() {
        return claimNumber;
    }

    public void setClaimNumber(String claimNumber) {
        this.claimNumber = claimNumber;
    }

    public BigDecimal getClaimedAmount() {
        return claimedAmount;
    }

    public void setClaimedAmount(BigDecimal claimedAmount) {
        this.claimedAmount = claimedAmount;
    }

    public String getClaimedCurrency() {
        return claimedCurrency;
    }

    public void setClaimedCurrency(String claimedCurrency) {
        this.claimedCurrency = claimedCurrency;
    }

    public LocalDate getIncidentDate() {
        return incidentDate;
    }

    public void setIncidentDate(LocalDate incidentDate) {
        this.incidentDate = incidentDate;
    }

    public ClaimStatus getStatus() {
        return status;
    }

    public void setStatus(ClaimStatus status) {
        this.status = status;
    }

    public LocalDate getSubmittedDate() {
        return submittedDate;
    }

    public void setSubmittedDate(LocalDate submittedDate) {
        this.submittedDate = submittedDate;
    }

    public String getPolicyId() {
        return policyId;
    }

    public void setPolicyId(String policyId) {
        this.policyId = policyId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ClaimJpaEntity that = (ClaimJpaEntity) o;
        return id != null && id.equals(that.id);
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
