package com.insurance.policy.domain.entity;

import com.insurance.policy.domain.valueobject.Coverage;
import com.insurance.policy.domain.valueobject.Money;
import com.insurance.policy.domain.valueobject.PolicyStatus;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for Policy domain entity.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 */
@DisplayName("Policy Domain Entity Tests")
class PolicyTest {

    @Test
    @DisplayName("Should create policy with valid inputs")
    void shouldCreatePolicyWithValidInputs() {
        // Arrange
        String customerId = "CUST-001";
        LocalDate effectiveDate = LocalDate.now().plusDays(1);
        List<Coverage> coverages = List.of(
                Coverage.of("Liability", 500.00, "USD"),
                Coverage.of("Collision", 300.00, "USD")
        );

        // Act
        Policy policy = new Policy(customerId, effectiveDate, coverages);

        // Assert
        assertNotNull(policy);
        assertEquals(customerId, policy.getCustomerId());
        assertEquals(effectiveDate, policy.getEffectiveDate());
        assertEquals(PolicyStatus.DRAFT, policy.getStatus());
        assertEquals(2, policy.getCoverages().size());
        assertEquals(Money.of(800.00, "USD"), policy.getTotalPremium());
        assertNotNull(policy.getPolicyNumber());
    }

    @Test
    @DisplayName("Should throw exception when customer ID is null")
    void shouldThrowExceptionWhenCustomerIdIsNull() {
        // Arrange
        LocalDate effectiveDate = LocalDate.now().plusDays(1);
        List<Coverage> coverages = List.of(Coverage.of("Liability", 500.00, "USD"));

        // Act & Assert
        assertThrows(IllegalArgumentException.class, () ->
                new Policy(null, effectiveDate, coverages)
        );
    }

    @Test
    @DisplayName("Should throw exception when effective date is in the past")
    void shouldThrowExceptionWhenEffectiveDateIsInPast() {
        // Arrange
        String customerId = "CUST-001";
        LocalDate effectiveDate = LocalDate.now().minusDays(1);
        List<Coverage> coverages = List.of(Coverage.of("Liability", 500.00, "USD"));

        // Act & Assert
        assertThrows(IllegalArgumentException.class, () ->
                new Policy(customerId, effectiveDate, coverages)
        );
    }

    @Test
    @DisplayName("Should throw exception when coverages list is empty")
    void shouldThrowExceptionWhenCoveragesIsEmpty() {
        // Arrange
        String customerId = "CUST-001";
        LocalDate effectiveDate = LocalDate.now().plusDays(1);
        List<Coverage> coverages = List.of();

        // Act & Assert
        assertThrows(IllegalArgumentException.class, () ->
                new Policy(customerId, effectiveDate, coverages)
        );
    }

    @Test
    @DisplayName("Should add coverage to draft policy")
    void shouldAddCoverageToDraftPolicy() {
        // Arrange
        String customerId = "CUST-001";
        LocalDate effectiveDate = LocalDate.now().plusDays(1);
        List<Coverage> coverages = List.of(Coverage.of("Liability", 500.00, "USD"));
        Policy policy = new Policy(customerId, effectiveDate, coverages);
        Coverage newCoverage = Coverage.of("Comprehensive", 400.00, "USD");

        // Act
        policy.addCoverage(newCoverage);

        // Assert
        assertEquals(2, policy.getCoverages().size());
        assertEquals(Money.of(900.00, "USD"), policy.getTotalPremium());
    }

    @Test
    @DisplayName("Should calculate correct total premium")
    void shouldCalculateCorrectTotalPremium() {
        // Arrange
        String customerId = "CUST-001";
        LocalDate effectiveDate = LocalDate.now().plusDays(1);
        List<Coverage> coverages = List.of(
                Coverage.of("Liability", 500.00, "USD"),
                Coverage.of("Collision", 300.00, "USD"),
                Coverage.of("Comprehensive", 200.00, "USD")
        );

        // Act
        Policy policy = new Policy(customerId, effectiveDate, coverages);

        // Assert
        assertEquals(Money.of(1000.00, "USD"), policy.getTotalPremium());
    }
}
