package com.insurance.policy.domain.valueobject;

import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 * ClaimAmount Value Object representing a claimed monetary amount.
 *
 * This is a Value Object (immutable) implemented as a Java Record.
 * Value Objects are defined by their attributes, not identity.
 * They are immutable and validate themselves on construction.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 * @version 1.0
 */
public record ClaimAmount(BigDecimal amount, String currency) {

    public static final ClaimAmount ZERO_USD = new ClaimAmount(BigDecimal.ZERO, "USD");

    /**
     * Compact constructor with validation.
     * Enforces invariants for the value object.
     *
     * @throws IllegalArgumentException if validation fails
     */
    public ClaimAmount {
        if (amount == null) {
            throw new IllegalArgumentException("Claim amount cannot be null");
        }
        if (amount.compareTo(BigDecimal.ZERO) < 0) {
            throw new IllegalArgumentException("Claim amount cannot be negative");
        }
        if (currency == null || currency.trim().isEmpty()) {
            throw new IllegalArgumentException("Currency is required");
        }
        // Ensure 2 decimal places for money
        amount = amount.setScale(2, RoundingMode.HALF_UP);
    }

    /**
     * Factory method for creating ClaimAmount with validation.
     *
     * @param amount the amount value
     * @param currency the currency code
     * @return validated ClaimAmount instance
     * @throws IllegalArgumentException if validation fails
     */
    public static ClaimAmount of(BigDecimal amount, String currency) {
        return new ClaimAmount(amount, currency);
    }

    /**
     * Factory method for creating ClaimAmount from double value.
     *
     * @param amount the amount as double
     * @param currency the currency code
     * @return validated ClaimAmount instance
     */
    public static ClaimAmount of(double amount, String currency) {
        return new ClaimAmount(BigDecimal.valueOf(amount), currency);
    }

    /**
     * Add two ClaimAmount values (must have same currency).
     *
     * @param other the other ClaimAmount to add
     * @return new ClaimAmount with summed values
     */
    public ClaimAmount add(ClaimAmount other) {
        if (!this.currency.equals(other.currency)) {
            throw new IllegalArgumentException("Cannot add different currencies");
        }
        return new ClaimAmount(this.amount.add(other.amount), this.currency);
    }

    /**
     * Multiply by a factor.
     *
     * @param factor the multiplication factor
     * @return new ClaimAmount with multiplied value
     */
    public ClaimAmount multiply(double factor) {
        return new ClaimAmount(this.amount.multiply(BigDecimal.valueOf(factor)), this.currency);
    }

    /**
     * Check if this amount is greater than another.
     *
     * @param other the other ClaimAmount to compare
     * @return true if this amount is greater
     */
    public boolean isGreaterThan(ClaimAmount other) {
        if (!this.currency.equals(other.currency)) {
            throw new IllegalArgumentException("Cannot compare different currencies");
        }
        return this.amount.compareTo(other.amount) > 0;
    }

    /**
     * Check if this amount is zero.
     *
     * @return true if amount is zero
     */
    public boolean isZero() {
        return this.amount.compareTo(BigDecimal.ZERO) == 0;
    }
}
