package com.insurance.policy.domain.valueobject;

import java.util.regex.Pattern;

/**
 * ClaimNumber Value Object representing a unique claim identifier.
 *
 * This is a Value Object (immutable) implemented as a Java Record.
 * Value Objects are defined by their attributes, not identity.
 * They are immutable and validate themselves on construction.
 *
 * Format: CLM-YYYY-NNNNNN (e.g., CLM-2025-000001)
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 * @version 1.0
 */
public record ClaimNumber(String value) {

    private static final Pattern CLAIM_NUMBER_PATTERN = Pattern.compile("^CLM-\\d{4}-\\d{6}$");

    /**
     * Compact constructor with validation.
     * Enforces invariants for the value object.
     *
     * @throws IllegalArgumentException if validation fails
     */
    public ClaimNumber {
        if (value == null || value.trim().isEmpty()) {
            throw new IllegalArgumentException("Claim number cannot be null or empty");
        }
        if (!CLAIM_NUMBER_PATTERN.matcher(value).matches()) {
            throw new IllegalArgumentException(
                "Claim number must match format CLM-YYYY-NNNNNN (e.g., CLM-2025-000001)");
        }
    }

    /**
     * Factory method for creating ClaimNumber with validation.
     *
     * @param value the claim number string
     * @return validated ClaimNumber instance
     * @throws IllegalArgumentException if validation fails
     */
    public static ClaimNumber of(String value) {
        return new ClaimNumber(value);
    }

    /**
     * Generate a new claim number for a given year and sequence.
     *
     * @param year the year
     * @param sequence the sequence number
     * @return a new ClaimNumber
     */
    public static ClaimNumber generate(int year, int sequence) {
        String formattedSequence = String.format("%06d", sequence);
        return new ClaimNumber("CLM-" + year + "-" + formattedSequence);
    }

    @Override
    public String toString() {
        return value;
    }
}
