package com.insurance.policy.domain.valueobject;

/**
 * Enum representing the status of a claim.
 *
 * Defines the lifecycle states of an insurance claim.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 */
public enum ClaimStatus {
    /**
     * Claim has been submitted but not yet reviewed.
     */
    SUBMITTED,

    /**
     * Claim is currently under review by adjusters.
     */
    UNDER_REVIEW,

    /**
     * Claim has been approved for payment.
     */
    APPROVED,

    /**
     * Claim has been rejected.
     */
    REJECTED,

    /**
     * Claim payment has been processed.
     */
    PAID
}
