package com.insurance.policy.domain.valueobject;

/**
 * Coverage Value Object representing an insurance coverage.
 *
 * Contains coverage type and premium amount.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 */
public record Coverage(String coverageType, Money premiumAmount) {

    /**
     * Compact constructor with validation.
     */
    public Coverage {
        if (coverageType == null || coverageType.trim().isEmpty()) {
            throw new IllegalArgumentException("Coverage type is required");
        }
        if (premiumAmount == null) {
            throw new IllegalArgumentException("Premium amount is required");
        }
    }

    public static Coverage of(String coverageType, double premiumAmount, String currency) {
        return new Coverage(coverageType, Money.of(premiumAmount, currency));
    }
}
