package com.insurance.policy.domain.valueobject;

import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 * Money Value Object representing amount and currency.
 *
 * Immutable and validates itself on construction.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 */
public record Money(BigDecimal amount, String currency) {

    public static final Money ZERO_USD = new Money(BigDecimal.ZERO, "USD");

    /**
     * Compact constructor with validation.
     */
    public Money {
        if (amount == null) {
            throw new IllegalArgumentException("Amount cannot be null");
        }
        if (amount.compareTo(BigDecimal.ZERO) < 0) {
            throw new IllegalArgumentException("Amount cannot be negative");
        }
        if (currency == null || currency.trim().isEmpty()) {
            throw new IllegalArgumentException("Currency is required");
        }
        // Ensure 2 decimal places for money
        amount = amount.setScale(2, RoundingMode.HALF_UP);
    }

    /**
     * Factory method.
     */
    public static Money of(double amount, String currency) {
        return new Money(BigDecimal.valueOf(amount), currency);
    }

    /**
     * Add two Money values (must have same currency).
     */
    public Money add(Money other) {
        if (!this.currency.equals(other.currency)) {
            throw new IllegalArgumentException("Cannot add different currencies");
        }
        return new Money(this.amount.add(other.amount), this.currency);
    }

    /**
     * Multiply by a factor.
     */
    public Money multiply(double factor) {
        return new Money(this.amount.multiply(BigDecimal.valueOf(factor)), this.currency);
    }

    public boolean isGreaterThan(Money other) {
        if (!this.currency.equals(other.currency)) {
            throw new IllegalArgumentException("Cannot compare different currencies");
        }
        return this.amount.compareTo(other.amount) > 0;
    }
}
