package com.insurance.policy.domain.valueobject;

import java.util.concurrent.atomic.AtomicLong;
import java.util.regex.Pattern;

/**
 * PolicyNumber Value Object.
 *
 * Format: POL-YYYY-NNNNNN
 * Example: POL-2025-000001
 *
 * Implemented as Java Record for immutability.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 */
public record PolicyNumber(String value) {

    private static final Pattern PATTERN = Pattern.compile("POL-\\d{4}-\\d{6}");
    private static final AtomicLong counter = new AtomicLong(0);

    /**
     * Compact constructor with validation.
     */
    public PolicyNumber {
        if (value == null || value.trim().isEmpty()) {
            throw new IllegalArgumentException("Policy number cannot be null or empty");
        }
        if (!PATTERN.matcher(value).matches()) {
            throw new IllegalArgumentException(
                    "Policy number must match format POL-YYYY-NNNNNN");
        }
    }

    /**
     * Generate a new policy number.
     *
     * @param year the year for the policy
     * @return new policy number
     */
    public static PolicyNumber generate(int year) {
        long sequence = counter.incrementAndGet();
        String value = String.format("POL-%d-%06d", year, sequence);
        return new PolicyNumber(value);
    }

    /**
     * Factory method for creating from string.
     */
    public static PolicyNumber of(String value) {
        return new PolicyNumber(value);
    }
}
