package com.insurance.policy.domain.valueobject;

/**
 * PolicyStatus enumeration.
 *
 * Represents the lifecycle states of an insurance policy.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 */
public enum PolicyStatus {
    DRAFT("Draft - not yet active"),
    ACTIVE("Active and in force"),
    EXPIRED("Expired - coverage ended"),
    CANCELLED("Cancelled before expiration");

    private final String description;

    PolicyStatus(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public boolean isTerminal() {
        return this == EXPIRED || this == CANCELLED;
    }
}
