package com.insurance.policy.application.exception;

import java.math.BigDecimal;

/**
 * Exception thrown when a claim amount is invalid.
 *
 * This is a domain exception that indicates the claimed amount violates business rules.
 * Examples: negative amount, zero amount, or amount exceeding policy limits.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 * @version 1.0
 */
public class InvalidClaimAmountException extends RuntimeException {

    private final BigDecimal claimedAmount;

    /**
     * Constructs a new InvalidClaimAmountException with the specified amount.
     *
     * @param claimedAmount the invalid claimed amount
     */
    public InvalidClaimAmountException(BigDecimal claimedAmount) {
        super(String.format("Invalid claim amount: %s", claimedAmount));
        this.claimedAmount = claimedAmount;
    }

    /**
     * Constructs a new InvalidClaimAmountException with a custom message.
     *
     * @param message the detail message
     * @param claimedAmount the invalid claimed amount
     */
    public InvalidClaimAmountException(String message, BigDecimal claimedAmount) {
        super(message);
        this.claimedAmount = claimedAmount;
    }

    /**
     * Get the invalid claimed amount.
     *
     * @return the claimed amount
     */
    public BigDecimal getClaimedAmount() {
        return claimedAmount;
    }
}
