package com.insurance.policy.application.exception;

/**
 * Exception thrown when a policy is not found.
 *
 * This is a domain exception that indicates a policy lookup failed.
 * It is typically thrown when trying to submit a claim for a non-existent policy.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 * @version 1.0
 */
public class PolicyNotFoundException extends RuntimeException {

    private final Long policyId;

    /**
     * Constructs a new PolicyNotFoundException with the specified policy ID.
     *
     * @param policyId the ID of the policy that was not found
     */
    public PolicyNotFoundException(Long policyId) {
        super(String.format("Policy with ID %d not found", policyId));
        this.policyId = policyId;
    }

    /**
     * Constructs a new PolicyNotFoundException with a custom message.
     *
     * @param message the detail message
     * @param policyId the ID of the policy that was not found
     */
    public PolicyNotFoundException(String message, Long policyId) {
        super(message);
        this.policyId = policyId;
    }

    /**
     * Get the policy ID that was not found.
     *
     * @return the policy ID
     */
    public Long getPolicyId() {
        return policyId;
    }
}
