package com.insurance.policy.infrastructure.adapter.persistence.mapper;

import com.insurance.policy.domain.entity.Claim;
import com.insurance.policy.domain.valueobject.ClaimAmount;
import com.insurance.policy.domain.valueobject.ClaimNumber;
import com.insurance.policy.infrastructure.adapter.persistence.entity.ClaimJpaEntity;

/**
 * Mapper between domain entity and JPA entity.
 *
 * Converts between Clean Architecture domain model and JPA persistence model.
 * This separation allows domain to remain framework-independent.
 *
 * @author Generated by BMAD Spring Boot Clean Architecture Generator
 * @version 1.0
 */
public class ClaimMapper {

    /**
     * Convert domain entity to JPA entity.
     *
     * @param domain the domain entity
     * @return the JPA entity
     */
    public static ClaimJpaEntity toJpa(Claim domain) {
        if (domain == null) {
            return null;
        }

        ClaimJpaEntity jpa = new ClaimJpaEntity();
        jpa.setId(domain.getId());
        jpa.setClaimNumber(domain.getClaimNumber().value());
        jpa.setClaimedAmount(domain.getClaimedAmount().amount());
        jpa.setClaimedCurrency(domain.getClaimedAmount().currency());
        jpa.setIncidentDate(domain.getIncidentDate());
        jpa.setStatus(domain.getStatus());
        jpa.setSubmittedDate(domain.getSubmittedDate());
        jpa.setPolicyId(domain.getPolicyId());
        return jpa;
    }

    /**
     * Convert JPA entity to domain entity.
     *
     * @param jpa the JPA entity
     * @return the domain entity
     */
    public static Claim toDomain(ClaimJpaEntity jpa) {
        if (jpa == null) {
            return null;
        }

        ClaimNumber claimNumber = ClaimNumber.of(jpa.getClaimNumber());
        ClaimAmount claimedAmount = ClaimAmount.of(jpa.getClaimedAmount(), jpa.getClaimedCurrency());

        Claim claim = new Claim(
            claimNumber,
            claimedAmount,
            jpa.getIncidentDate(),
            jpa.getPolicyId()
        );

        // Use reflection to set ID and submittedDate (private setters)
        try {
            java.lang.reflect.Field idField = Claim.class.getDeclaredField("id");
            idField.setAccessible(true);
            idField.set(claim, jpa.getId());

            java.lang.reflect.Field submittedDateField = Claim.class.getDeclaredField("submittedDate");
            submittedDateField.setAccessible(true);
            submittedDateField.set(claim, jpa.getSubmittedDate());

            java.lang.reflect.Field statusField = Claim.class.getDeclaredField("status");
            statusField.setAccessible(true);
            statusField.set(claim, jpa.getStatus());
        } catch (Exception e) {
            throw new RuntimeException("Failed to map JPA entity to domain entity", e);
        }

        return claim;
    }

    /**
     * Update JPA entity from domain entity (for updates).
     *
     * @param jpa the JPA entity to update
     * @param domain the source domain entity
     */
    public static void updateJpaFromDomain(ClaimJpaEntity jpa, Claim domain) {
        jpa.setClaimNumber(domain.getClaimNumber().value());
        jpa.setClaimedAmount(domain.getClaimedAmount().amount());
        jpa.setClaimedCurrency(domain.getClaimedAmount().currency());
        jpa.setIncidentDate(domain.getIncidentDate());
        jpa.setStatus(domain.getStatus());
        jpa.setSubmittedDate(domain.getSubmittedDate());
        jpa.setPolicyId(domain.getPolicyId());
    }
}
